# name: Deploy docs

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - run: npm ci

#       - run: npm run build

#       - name: Deploy storybook
#         working-directory: ./packages/docs
#         run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
#         env:
#           GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}

# name: 'Chromatic'

# on: push

# jobs:
#   chromatic:
#     name: Run Chromatic
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Install dependencies
#         # ⚠️ See your package manager's documentation for the correct command to install dependencies in a CI environment.
#         run: npm ci
#       - name: Run Chromatic
#         uses: chromaui/action@latest
#         with:
#           # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
#           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
#           workingDir: packages/docs

# .github/workflows/deploy-github-pages.yaml

name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main' # Substitua pelo branch que você deseja usar

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v4

      # Configurar o Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instalar dependências
      - run: npm ci
        working-directory: ./packages/docs

      # Construir o Storybook
      - run: npm run build-storybook
        working-directory: ./packages/docs

      # Publicar o Storybook no GitHub Pages
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: /docs # Certifique-se de que este caminho está correto
          checkout: false
        # O `working-directory` foi removido aqui porque não é suportado pelo action.
