name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala as dependências
      - run: npm ci

      # Builda o projeto principal
      - run: npm run build
        env: 
          TURBO_TOKEN: 71jgdGL0mIlWsM53GKAAByOM
          TURBO_TEAM: jocabadasss-projects





      # Arquiva o build do Storybook com um nome de artefato único usando o Bitovi
      - name: Upload Storybook to GitHub Pages
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build
          path: ./packages/docs/storybook-static


