name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: npm run build-storybook
        working-directory: packages/docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: packages/docs/storybook-static
